# Generated by Django 4.1.1 on 2023-02-03 20:38

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0002_rename_image_id_perevalimages_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perevaluser',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
